13 1 middleware
thinknetica-django-lab-03/viktorshm-github pull request #112
Opened 2021-07-09 16:18 UTC by viktorshm-github

Closes #97

2021-07-10 08:14 UTC, mikhailborodin requested changes

2021-07-10 08:14 UTC, mikhailborodin commented on ecommerce/main/middleware.py
> +    def process_view(self, request, view_func, view_args, view_kwargs):
middleware должен добавлять данные в request, если user_agent мобильный, и дальше передавать request в контроллеры. У вас просто возвращает HttpResponse, поэтому логика должна быть в другом методе и должен быть более широкий список user_agents, не у всех есть mobile в названии https://deviceatlas.com/blog/mobile-browser-user-agent-strings

2021-07-11 06:20 UTC, viktorshm-github commented on ecommerce/main/middleware.py
> +    def process_view(self, request, view_func, view_args, view_kwargs):
Поправил. Спасибо!

2021-07-12 21:02 UTC, mikhailborodin approved these changes

2021-07-13 05:36 UTC, merged