13 2 logging
thinknetica-django-lab-03/viktorshm-github pull request #113
Opened 2021-07-12 14:59 UTC by viktorshm-github

Closes #99

2021-07-13 05:45 UTC, mikhailborodin requested changes

2021-07-13 05:45 UTC, mikhailborodin commented on ecommerce/ecommerce/settings.py
> +ALLOWED_HOSTS = '*'
это должен быть массив

2021-07-13 06:12 UTC, viktorshm-github commented on ecommerce/ecommerce/settings.py
> +ALLOWED_HOSTS = '*'
Спасибо! Поправил.

2021-07-15 05:43 UTC, mikhailborodin approved these changes

2021-07-15 08:37 UTC, merged