14 4 crud methods
thinknetica-django-lab-03/viktorshm-github pull request #118
Opened 2021-07-16 20:36 UTC by viktorshm-github

Closes #104

2021-07-17 12:50 UTC, mikhailborodin requested changes

2021-07-17 12:50 UTC, mikhailborodin commented on ecommerce/main/views.py
> +class AdThingsDetail(APIView):
чтобы не писать каждый метод самостоятельно, в стандартных случаях лучше использовать ModelViewSet

2021-07-18 05:56 UTC, viktorshm-github commented on ecommerce/main/views.py
> +class AdThingsDetail(APIView):
Оставил предыдущий вариант и добавил на adthings1 вариант с ModelViewSet.

Спасибо!

2021-07-18 10:57 UTC, mikhailborodin approved these changes

2021-07-18 11:09 UTC, merged