4 1 filtering and pagination
thinknetica-django-lab-03/viktorshm-github pull request #33
Opened 2021-06-04 13:18 UTC by viktorshm-github

Closes #20

2021-06-05 20:43 UTC, mikhailborodin requested changes

2021-06-05 20:43 UTC, mikhailborodin commented on ecommerce/main/models.py
> +        return
он не должен быть пустым, надо возвращать строку например '/category/{}/'.format(self.slug) или с использованием reverse. Вижу что вы ниже так и сделали

2021-06-05 20:43 UTC, mikhailborodin commented on ecommerce/main/models.py
>      Condition = models.TextChoices('Condition', 'NEW USED')
`Condition =` должен быть с маленькой буквы

2021-06-05 20:43 UTC, mikhailborodin commented on ecommerce/main/views.py
> +        except:
просто except использовать не рекомендуется, надо добавлять какие типы ошибок обрабатывает этот except

2021-06-07 06:46 UTC, viktorshm-github commented on ecommerce/main/models.py
>      Condition = models.TextChoices('Condition', 'NEW USED')
Это же класс множественного выбора. Ниже есть отдельное поле condition

2021-06-07 06:46 UTC, viktorshm-github commented on ecommerce/main/models.py
> +        return
Поправил. Спасибо!

2021-06-07 20:28 UTC, mikhailborodin approved these changes

2021-06-09 10:51 UTC, merged