5 2 django all auth
thinknetica-django-lab-03/viktorshm-github pull request #48
Opened 2021-06-09 14:28 UTC by viktorshm-github

Closes #39

2021-06-10 20:25 UTC, mikhailborodin requested changes

2021-06-10 20:25 UTC, mikhailborodin commented on ecommerce/main/forms.py
> +        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))
расчет определения возраста решили не менять?

2021-06-11 10:53 UTC, viktorshm-github commented on ecommerce/main/forms.py
> +        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))
Поправил в 5.4 Или внести в эту ветку?

2021-06-11 20:18 UTC, mikhailborodin approved these changes

2021-06-11 20:21 UTC, mikhailborodin commented on ecommerce/main/forms.py
> +        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))
в 5.4 тот же код или я не там смотрю?

2021-06-12 10:21 UTC, viktorshm-github commented on ecommerce/main/forms.py
> +        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))
Почему-то в 5.3 есть, а в 5.4 не попало. Поправил уже в 6.2 точно попадёт.

2021-06-12 10:22 UTC, merged