5 3 user groups
thinknetica-django-lab-03/viktorshm-github pull request #49
Opened 2021-06-10 17:35 UTC by viktorshm-github

Closes #41

2021-06-10 20:28 UTC, mikhailborodin requested changes

2021-06-10 20:28 UTC, mikhailborodin commented on ecommerce/main/models.py
> +        instance.groups.add(Group.objects.get(name='common users'))
если такой группы нет, то будет ошибка

2021-06-11 11:16 UTC, viktorshm-github commented on ecommerce/main/models.py
> +        instance.groups.add(Group.objects.get(name='common users'))
Поправил

2021-06-11 20:18 UTC, mikhailborodin approved these changes

2021-06-12 10:22 UTC, merged