6 1 e mails
thinknetica-django-lab-03/viktorshm-github pull request #51
Opened 2021-06-11 15:57 UTC by viktorshm-github

Closes #38

2021-06-12 21:55 UTC, mikhailborodin commented
следующую ветку начните от main, а то в пул реквесте уже 57 изменений, сложно проверять задание

2021-06-12 21:58 UTC, mikhailborodin requested changes

2021-06-12 21:58 UTC, mikhailborodin commented on ecommerce/main/signals.py
> +        emailSender.send_mail_to_new_user(subject, text_content, from_email, to, html_content=html_content)
to должно быть значением мэйла нового пользователя

2021-06-15 05:28 UTC, viktorshm-github commented on ecommerce/main/signals.py
> +        emailSender.send_mail_to_new_user(subject, text_content, from_email, to, html_content=html_content)
Спасибо! Поправил.

2021-06-16 06:42 UTC, mikhailborodin approved these changes

2021-06-23 14:08 UTC, merged