7 4 celery beat
thinknetica-django-lab-03/viktorshm-github pull request #68
Opened 2021-06-21 15:47 UTC by viktorshm-github

Closes #59

2021-06-21 21:24 UTC, mikhailborodin requested changes

2021-06-21 21:24 UTC, mikhailborodin commented on ecommerce/ecommerce/celery.py
> +        'schedule': crontab(),
пустое расписание

2021-06-21 21:24 UTC, mikhailborodin commented on ecommerce/main/apps.py
> +    def ready(self):
функцию можно убрать совсем

2021-06-22 12:00 UTC, viktorshm-github commented on ecommerce/ecommerce/celery.py
> +        'schedule': crontab(),
Поправил. Это я тестировал =)

2021-06-22 12:06 UTC, viktorshm-github commented on ecommerce/main/apps.py
> +    def ready(self):
Удалил всё, что было в комментах

2021-06-24 05:56 UTC, mikhailborodin approved these changes

2021-06-24 09:21 UTC, merged